site_name: Eetu Niemi – Publications, Presentations & Public Appearances
site_description: Curated list of Eetu Niemi’s professional, academic, and creative works, including books, articles, talks, and media appearances on enterprise architecture, consulting, and work life, as well as novels, children's books and short stories 
site_author: Eetu Niemi, PhD
repo_url: https://github.com/eetuniemiphd/eetuniemi/
site_url: https://publications.eetuniemi.fi/
theme:
  name: material
  language: en
  logo: assets/eetu-niemi-publications-logo.png
  favicon: assets/eetu-niemi-publications-favicon.png
  palette:
    primary: black
    accent: deep orange
  font:
    text: Open Sans
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.highlight

plugins:
  - search:
      lang: [en, fi]

nav:
  - KOTI / HOME: index.md
  - Julkaisut / Publications: publications.md
  - Esitykset / Presentations: presentations.md
  - Media ja esiintymiset / Appearances and Media: appearances-media.md
