site_name: Eetu Niemi — Publications, Presentations & Public Appearances
site_description: Curated list of Eetu Niemi’s professional, academic, and creative works, including books, articles, short stories, talks, and media appearances on enterprise architecture, consulting, and work life
site_author: Eetu Niemi, PhD
repo_url: https://github.com/eetuniemiphd/eetuniemi
theme:
  name: material
  language: en
  logo:
  palette:
    primary: black
    accent: indigo
  font:
    text: Open Sans
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.highlight
    - content.code.copy

nav:
  - HOME: index.md
  - PUBLICATIONS: publications-eetu-niemi.md
  - PRESENTATIONS: presentations-eetu-niemi.md
  - APPEARANCES AND MEDIA: appearances-media-eetu-niemi.md
